import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "MG Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <div className="flex flex-col">
          <div className="flex-none">
            <div className="fixed top-0 flex w-16 w-screen flex-row items-center justify-center space-x-5 bg-gradient-to-r from-lightPink to-red ">
              <Header />
            </div>
          </div>
          <div className="flex-1 pt-12">
            <main
              className="min-h-screen bg-gradient-to-b
               from-lightBlue  to-darkBlue bg-center text-white"
            >
              <TRPCReactProvider cookies={cookies().toString()}>
                {children}
              </TRPCReactProvider>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
